### ISSUE TITLE
Trouble installing numpy and scipy from requirements

### ISSUE THREAD

**Issue by PeterSR** [onichandame/python-test-action#1]
Trying to install `numpy` and `scipy` to use in Python unit test.

Using the following action `.github/workflows/python-test.yml`:

```yaml
name: Test
on:
  push:
    branches: '*'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install package
        run: |
          sudo apt-get -y install gcc gfortran python-dev libopenblas-dev liblapack-dev cython
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Test
        uses: onichandame/python-test-action@0.0.0
```

`requirements.txt`:

```
numpy~=1.20.1
scipy~=1.6.1
```

It fails with the following output: 
[output.txt](https://github.com/onichandame/python-test-action/files/6166079/output.txt)

The Ubuntu packages installed are based on https://docs.scipy.org/doc/scipy/reference/building/linux.html#debian-ubuntu, but I have also tried a bunch of other packages. 

I suspect that packages installed earlier are not visible for this action when it is running. 

Any ideas?
